"""'base_002'

Revision ID: 800842b47011
Revises: acda87d627fc
Create Date: 2018-09-04 16:44:55.760994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800842b47011'
down_revision = 'acda87d627fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botdetail_bot_id'), 'botdetail', ['bot_id'], unique=False)
    op.create_index(op.f('ix_botdetail_order'), 'botdetail', ['order'], unique=False)
    op.add_column('chatdetail', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chatdetail_chat_id'), 'chatdetail', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chatdetail_order'), 'chatdetail', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatdetail_order'), table_name='chatdetail')
    op.drop_index(op.f('ix_chatdetail_chat_id'), table_name='chatdetail')
    op.drop_column('chatdetail', 'order')
    op.drop_index(op.f('ix_botdetail_order'), table_name='botdetail')
    op.drop_index(op.f('ix_botdetail_bot_id'), table_name='botdetail')
    op.drop_table('botdetail')
    # ### end Alembic commands ###
