"""base_003

Revision ID: a4ed93390b19
Revises: 800842b47011
Create Date: 2018-09-17 20:48:50.422846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ed93390b19'
down_revision = '800842b47011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chatdetail_chat_id'), 'chatdetail', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chatdetail_order'), 'chatdetail', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatdetail_order'), table_name='chatdetail')
    op.drop_index(op.f('ix_chatdetail_chat_id'), table_name='chatdetail')
    # ### end Alembic commands ###
